server/RankingWebApp/Models/ErrorViewModel.cs
namespace ChatWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

server/RankingWebApp/Models/Rank.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ChatWebApp.Models
{
    public class Rank
    {
        [Key]
        [DisplayName("User name")]
        [Required]
        public string Username { get; set; }

        [Required]
        [DisplayName("Rank")]
        [Range(1,5, ErrorMessage="The rank must be between 1 and 5")]
        public int NumeralRank { get; set; }

        public string? Feedback { get; set; }

        [DisplayName("Time")]
        public string? SubmitTime { get; set; }         
    }
}

server/RankingWebApp/Controllers/RanksController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChatWebApp.Data;
using ChatWebApp.Models;
using ChatWebApp.Services;

namespace ChatWebApp.Controllers
{
    public class RanksController : Controller
    {
        private IRankService _service;
        private static ChatWebAppContext _context;

        public RanksController(ChatWebAppContext context)
        {
            _context = context;
            _service = new RankService();
        }

        // GET: Ranks
        public async Task<IActionResult> Index()
        {
            ViewBag.Ranks = await _service.Average(_context);
            return View(await _service.GetAll(_context));
        }

        // GET: Ranks/Details/5
        public async Task<IActionResult> Details(string Username)
        {
            if (Username == null)
                return NotFound();
            Rank rank = await _service.Get(_context, Username);
            if (rank == null)
                return BadRequest();
            return View(await _service.Get(_context, Username));
        }

        // GET: Ranks/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Ranks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Username,NumeralRank,Feedback")] Rank rank)
        {

            if (ModelState.IsValid)
            {
                if (await _service.Get(_context, rank.Username) != null)
                {
                    ModelState.AddModelError("Username", "This user already sent a feedback");
                    return View(rank);
                }
                _service.Add(_context, rank.Username, rank.NumeralRank, rank.Feedback);
                return RedirectToAction(nameof(Index));
            }
            return View(rank);
        }

        // GET: Ranks/Edit/5
        /*        public IActionResult Edit(string Username, int NumeralRank, string Feedback, string SubmitTime)
        */
        public async Task<IActionResult> Edit(string Username)
        {
            if (Username == null)
            {
                return NotFound();
            }
            return View(await _service.Get(_context, Username));
        }

        // POST: Ranks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string Username, [Bind("Username,NumeralRank,Feedback,SubmitTime")] Rank rank)
        {
            _service.Edit(_context, Username, rank.NumeralRank, rank.Feedback, rank.SubmitTime);
            return RedirectToAction(nameof(Index));
        }

        // GET: Ranks/Delete/5
        public async Task<IActionResult> Delete(string Username)
        {
            if (Username == null)
            {
                return NotFound();
            }

            var rank = await _service.Get(_context, Username);
            if (rank == null)
            {
                return NotFound();
            }

            return View(rank);
        }

        // POST: Ranks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string Username)
        {
            _service.Delete(_context, Username);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string query)
        {
            if (string.IsNullOrEmpty(query))
                return Json(await _service.GetAll(_context));
            List<Rank> results = new List<Rank>();
            List<Rank> ranks = await _service.GetAll(_context);
            int length = ranks.Count();
            for (int i = 0; i < length; i++)
            {
                if (ranks[i].Feedback != null && ranks[i].Feedback.Contains(query))
                    results.Add(ranks[i]);
            }
            return Json(results);
        }
    }
}

server/RankingWebApp/Views/Ranks/Create.cshtml
@model ChatWebApp.Models.Rank

@{
	ViewData["Title"] = "Create";
}

<div class="default">

	<h3 class="header-text">Add your rank</h3>

	<hr />
	<div class="row center">
		<div class="col-md-4 center">
			<form class="center" asp-action="Create">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<div class="form-group">
					<label asp-for="Username" class="control-label def-text"></label>
					<input asp-for="Username" class="form-control" />
					<span asp-validation-for="Username" id="username-validation" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="NumeralRank" class="control-label def-text"></label>
					<input asp-for="NumeralRank" class="form-control" />
					<span asp-validation-for="NumeralRank" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Feedback" class="control-label def-text"></label>
					<input asp-for="Feedback" class="form-control" />
					<span asp-validation-for="Feedback" class="text-danger"></span>
				</div>
				<div class="form-group">
					@*                <label asp-for="SubmitTime" class="control-label"></label>
					*@                <input type="hidden" asp-for="SubmitTime" class="form-control" />
					@*                <span asp-validation-for="SubmitTime" class="text-danger"></span>
					*@
				</div>
				<div class="form-group">
					<input type="submit" value="Create" class="btn btn-primary" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-action="Index">Back to List</a>
	</div>
</div>

@section Scripts {
    @{
	await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

server/RankingWebApp/Views/Ranks/Delete.cshtml
@model ChatWebApp.Models.Rank

@{
	ViewData["Title"] = "Delete";
}

<div class="default">


	<h3 class="header-text">Delete @Html.DisplayFor(model => model.Username)'s rank</h3>

	<h4 class="def-text" >Are you sure you want to delete this?</h4>
	<div>
		<hr />
		<dl class="row">
			<dt class="col-sm-2 def-text">
				@Html.DisplayNameFor(model => model.Username)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.Username)
			</dd>
			<dt class="col-sm-2 def-text">
				@Html.DisplayNameFor(model => model.NumeralRank)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.NumeralRank)
			</dd>
			<dt class="col-sm-2 def-text">
				@Html.DisplayNameFor(model => model.Feedback)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.Feedback)
			</dd>
			<dt class="col-sm-2 def-text">
				@Html.DisplayNameFor(model => model.SubmitTime)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.SubmitTime)
			</dd>
		</dl>

		<form asp-action="Delete">
			<input type="hidden" asp-for="Username" />
			<input type="submit" value="Delete" class="btn btn-danger" /> |
			<a asp-action="Index">Back to List</a>
		</form>
	</div>
</div>

server/RankingWebApp/Views/Ranks/Details.cshtml
@model ChatWebApp.Models.Rank

@{
	ViewData["Title"] = "Details";
}

<div class="default">

	<h3 class="header-text">@Html.DisplayFor(model => model.Username)'s rank</h3>

	<div>
		<hr />
		<dl class="row">
			<dt class="col-sm-2 def-text">
				@Html.DisplayNameFor(model => model.NumeralRank)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.NumeralRank)
			</dd>
			<dt class="col-sm-2 def-text ">
				@Html.DisplayNameFor(model => model.Feedback)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.Feedback)
			</dd>
			<dt class="col-sm-2 def-text">
				@Html.DisplayNameFor(model => model.SubmitTime)
			</dt>
			<dd class="col-sm-10 def-text to-left">
				@Html.DisplayFor(model => model.SubmitTime)
			</dd>
		</dl>
	</div>
	<div>
		<a asp-action="Edit" asp-route-Username="@Model?.Username">Edit</a> |
		<a asp-action="Index">Back to List</a>
	</div>
</div>

server/RankingWebApp/Views/Ranks/Edit.cshtml
@model ChatWebApp.Models.Rank
<div class="default">

	@{
		ViewData["Title"] = "Edit";
	}

	<h3 class="header-text">Edit @Html.DisplayFor(model => model.Username)'s rank</h3>

	<hr />
	<div class="row center">
		<div class="col-md-4">
			<form asp-action="Edit">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="Username" />
				<div class="form-group">
					<label asp-for="NumeralRank" class="control-label def-text"></label>
					<input asp-for="NumeralRank" class="form-control" />
					<span asp-validation-for="NumeralRank" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Feedback" class="control-label def-text"></label>
					<input asp-for="Feedback" class="form-control def-text" />
					<span asp-validation-for="Feedback" class="text-danger"></span>
				</div>
				<div type="hidden" class="form-group">
@*					<label asp-for="SubmitTime" class="control-label"></label>
*@					<input type="hidden" asp-for="SubmitTime" class="form-control def-text" />
@*					<span asp-validation-for="SubmitTime" class="text-danger"></span>
*@				</div>
				<div class="form-group">
					<input type="submit" value="Save" class="btn btn-primary" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-action="Index">Back to List</a>
	</div>
</div>
@*@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
	}*@

server/RankingWebApp/Views/Ranks/Index.cshtml
@model IEnumerable<ChatWebApp.Models.Rank>

@{
    ViewData["Title"] = "Index";
}
<div class="default">
    <h3 class="header-text">Application rankings</h3>
    <hr />
    <div class="def-text">The average rank of the app is @ViewBag.Ranks.ToString("0.00") </div>
    <hr />
    <form id="searchInRanks" asp-action="Search">
        <input name="query" id="searchQuery" />
        <input type="submit" value="Search" class="btn btn-primary btn-sm" />
    </form>
    <hr />
    <p>
        <a asp-action="Create">Add a review</a>
    </p>
    <table style="width:100%" class="table">
        <thead>
            <tr>
                <th id="username-col">
                    <div class="def-text">@Html.DisplayNameFor(model => model.Username)</div>
                </th>
                <th id="numeral-rank-col" >
                    <div class="def-text">@Html.DisplayNameFor(model => model.NumeralRank)</div>
                </th>
                <th id="feedback-col">
                    <div class="def-text">@Html.DisplayNameFor(model => model.Feedback)</div>
                </th>
                <th id="time-col">
                    <div class="def-text">@Html.DisplayNameFor(model => model.SubmitTime)</div>
                </th>
                <th id="options-col"></th>
            </tr>
        </thead>
        <tbody id="theBody">
            @foreach (var item in Model)
            {
                <tr =>
                    <td>
                        <div class="def-text wrap-text">@Html.DisplayFor(modelItem => item.Username)</div>
                    </td>
                    <td>
                        <div class="def-text wrap-text">@Html.DisplayFor(modelItem => item.NumeralRank)</div>
                    </td>
                    <td>
                        <div class="def-text wrap-text">@Html.DisplayFor(modelItem => item.Feedback)</div>
                    </td>
                    <td>
                        <div class="def-text wrap-text">@Html.DisplayFor(modelItem => item.SubmitTime)</div>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-Username="@item.Username">Edit</a> |
                        <a asp-action="Details" asp-route-Username="@item.Username">Details</a> |
                        <a asp-action="Delete" asp-route-Username="@item.Username">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script type="text/html" id="searchTemplate">
                <tr>
                    <td>
                        <div class="def-text wrap-text">{username}</div>
                    </td>
                    <td>
                        <div class="def-text wrap-text">{numeralRank}</div>
                    </td>
                    <td>
                        <div class="def-text wrap-text">{feedback}</div>
                    </td>
                    <td>
                        <div class="def-text wrap-text">{submitTime}</div>
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-Username="{username}">Edit</a> |
                        <a asp-action="Details" asp-route-Username="{username}">Details</a> |
                        <a asp-action="Delete" asp-route-Username="{username}">Delete</a>
                    </td>
                </tr>
     </script>
    <script src="~/js/RanksSearch.js"></script>
}

server/RankingWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChatWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
@*    <link rel="stylesheet" href="../Views/Shared/_Layout.cshtml.css" />
*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand def-text" asp-area="" asp-controller="Ranks" asp-action="Index">ChatWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark def-text"  href="http://localhost:3000/">Log-in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link def-text" href="http://localhost:3000/signUp">Sign-up</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>